name: build_and_test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  windows:
    runs-on: windows-2019
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Windows VS2019
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && msbuild.exe projects/vs2019/ClangBuildAnalyzer.sln /p:Configuration=Debug /p:CL_MPCount=2
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && msbuild.exe projects/vs2019/ClangBuildAnalyzer.sln /p:Configuration=Release /p:CL_MPCount=2
        build\ClangBuildAnalyzer.exe --test tests
      shell: cmd
    - uses: actions/upload-artifact@v1
      with:
        name: ClangBuildAnalyzer-win.exe
        path: build/ClangBuildAnalyzer.exe

  mac:
    runs-on: macOS-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: macOS Xcode 11.1
      run: |
        xcodebuild -project projects/xcode/ClangBuildAnalyzer.xcodeproj -configuration Debug build
        xcodebuild -project projects/xcode/ClangBuildAnalyzer.xcodeproj -configuration Release build
        projects/xcode/build/Release/ClangBuildAnalyzer --test tests
    - uses: actions/upload-artifact@v1
      with:
        name: ClangBuildAnalyzer-mac
        path: projects/xcode/build/Release/ClangBuildAnalyzer

  linux:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Ubuntu16 Gcc7
      env:
        CC: gcc-7
        CXX: g++-7
      run: |
        mkdir buildCmake
        cd buildCmake
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j 2
        cd ..
        buildCmake/ClangBuildAnalyzer --test tests
        make -f projects/make/Makefile -j 2
        build/ClangBuildAnalyzer --test tests
    - uses: actions/upload-artifact@v1
      with:
        name: ClangBuildAnalyzer-linux
        path: build/ClangBuildAnalyzer

