name: build_and_test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  windows:
    runs-on: windows-2019
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: Trass3r/setup-cpp@master
    - name: build
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        msbuild.exe projects/vs2019/ClangBuildAnalyzer.sln /p:Configuration=Debug /p:UseMultiToolTask=true
        msbuild.exe projects/vs2019/ClangBuildAnalyzer.sln /p:Configuration=Release /p:UseMultiToolTask=true
    - name: test
      run: |
        build\ClangBuildAnalyzer.exe --test tests
      shell: cmd
    - uses: actions/upload-artifact@v2
      with:
        name: ClangBuildAnalyzer-win.exe
        path: build/ClangBuildAnalyzer.exe

  mac:
    runs-on: macos-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        xcodebuild -project projects/xcode/ClangBuildAnalyzer.xcodeproj -configuration Debug build
        xcodebuild -project projects/xcode/ClangBuildAnalyzer.xcodeproj -configuration Release build
    - name: test
      run: |
        projects/xcode/build/Release/ClangBuildAnalyzer --test tests
    - uses: actions/upload-artifact@v2
      with:
        name: ClangBuildAnalyzer-mac
        path: projects/xcode/build/Release/ClangBuildAnalyzer

  linux:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: Trass3r/setup-cpp@master
    - name: build
      run: |
        mkdir buildCmake
        cd buildCmake
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j 2
        cd ..
        make -f projects/make/Makefile -j 2
    - name: test
      run: |
        buildCmake/ClangBuildAnalyzer --test tests
        build/ClangBuildAnalyzer --test tests
    - uses: actions/upload-artifact@v2
      with:
        name: ClangBuildAnalyzer-linux
        path: build/ClangBuildAnalyzer

